version: '3.1'

services:

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=hello
      - POSTGRES_USER=hello
      - POSTGRES_DB=gh
    networks:
        - connection

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ~/grafana-data:/var/lib/grafana
    networks:
        - connection

  backend:
    environment:
      - POSTGRES_SERVER=postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - connection
    working_dir: /app
    restart: always

  frontend:
    environment:
      - BACKEND_URL=backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - connection
    working_dir: /app
    command: streamlit run frontend.py
    restart: always

networks:
  connection:
    driver: bridge